ktor:
  application:
    modules:
      - org.delcom.ApplicationKt.module
  deployment:
    # Gunakan PORT dari server, kalau gak ada cari APP_PORT, kalau gak ada baru pakai 8000
    port: ${PORT:-${APP_PORT:-8000}}
    # Gunakan HOST dari server, kalau gak ada default ke 0.0.0.0 (ini paling aman buat deploy)
    host: ${APP_HOST:-0.0.0.0}

  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

  jwt:
    secret: "${JWT_SECRET}"

  app:
    baseUrl: ${APP_URL}